//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppifyMiddleware.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopifyProduct
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ProductType { get; set; }
        public string Vendor { get; set; }
        public string BodyHtml { get; set; }
        public bool Publish { get; set; }
        public long ShopifyId { get; set; }
        public System.DateTime CreatedDateUtc { get; set; }
        public Nullable<System.DateTime> LastUpdatedUtc { get; set; }
        public byte UploadStatus { get; set; }
    }
}
